Vagrant.configure("2") do |config|
    config.vbguest.auto_update = false
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
        vb.check_guest_additions = false
    end

    config.vm.define "puppetmaster" do |puppetmaster|
        puppetmaster.vm.provider "virtualbox" do |vb|
            vb.memory = 4096
            vb.cpus = 1
            vb.check_guest_additions = false
        end
        puppetmaster.vm.box = "ubuntu/focal64"
        puppetmaster.vm.network "private_network", ip: "172.29.128.2"

        puppetmaster.vm.provision "shell", path: "node_provision.sh"
        puppetmaster.vm.provision "shell", path: "puppetmaster_node_provision.sh"

    end

    config.vm.define "puppetclient" do |puppetclient|
        puppetclient.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 1
            vb.check_guest_additions = false
        end
        puppetclient.vm.box = "ubuntu/focal64"
        puppetclient.vm.network "private_network", ip: "172.29.128.3"

        puppetclient.vm.provision "shell", path: "node_provision.sh"
        puppetclient.vm.provision "shell", path: "agent_node_provision.sh"
    end
end
